spring:
  application:
    name: configuration
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:configurations

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
