eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://discovery-service:8761/eureka/}
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      default:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 2s
    instances:
      default:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true