server:
  port: 8060

spring:
  application:
    name: booking-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://postgres-db:5432/booking}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: validate
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: ${LIQUIBASE_ENABLED:true}

  data:
    redis:
      host: ${REDIS_HOST:redis-db}
      port: ${REDIS_PORT:6379}
      timeout: 60000

application:
  config:
    customer-url: ${CUSTOMER_SERVICE_URL:http://customer-service:8090/api/v1/customers}
    flights-url: ${FLIGHT_SERVICE_URL:http://flights-service:8070/api/v1/flights}