server:
  port: 8070

spring:
  application:
    name: flights-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://postgres-db:5432/flights}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: validate
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: ${LIQUIBASE_ENABLED:true}